name: Crawl ITviec Weekly

on:
  schedule:
    - cron: "0 0 * * 0"  # Chạy mỗi Chủ nhật 0h UTC
  workflow_dispatch:      # Cho phép bấm "Run workflow" thủ công

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager

      - name: Run crawler
        env:
          ITVIEC_COOKIE: ${{ secrets.ITVIEC_COOKIE }}
        run: python itviec_crawler_gh.py

      - name: Upload to Azure Blob
        uses: azure/cli@v2
        with:
          inlineScript: |
            az storage blob upload \
              --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
              --account-key ${{ secrets.AZURE_STORAGE_KEY }} \
              --container-name '$web' \
              --file jobs_data_with_salary.json \
              --name jobs_data_with_salary.json \
              --overwrite true
