name: Crawl ITviec Weekly

on:
  schedule:
    - cron: "0 0 * * 0"  # Chạy mỗi Chủ nhật 0h UTC
  workflow_dispatch:      # Cho phép bấm "Run workflow" thủ công

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager

      - name: Run crawler
        env:
          ITVIEC_COOKIE: ${{ secrets.ITVIEC_COOKIE }}
        run: python itviec_crawler_gh.py

      - name: Upload to Azure Storage
        uses: bacongobbler/azure-blob-storage-upload@v1.4.1
        with:
          source_dir: .
          container_name: '$web'
          connection_string: DefaultEndpointsProtocol=https;AccountName=${{ secrets.AZURE_STORAGE_ACCOUNT }};AccountKey=${{ secrets.AZURE_STORAGE_KEY }};EndpointSuffix=core.windows.net
