name: Crawl ITviec Weekly

on:
  schedule:
    - cron: "0 3 * * 1"   # Mỗi thứ Hai lúc 03:00 UTC (10h sáng VN)
  workflow_dispatch:       # Cho phép chạy thủ công

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run crawler
        env:
          ITVIEC_COOKIE: ${{ secrets.ITVIEC_COOKIE }}
        run: python itviec_crawler_gh.py

      - name: Upload to Azure Blob
        uses: azure/cli@v2
        with:
          inlineScript: |
            az storage blob upload \
              --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
              --account-key ${{ secrets.AZURE_STORAGE_KEY }} \
              --container-name ${{ secrets.AZURE_CONTAINER }} \
              --file jobs.json \
              --name "jobs-$(date +'%Y-%m-%d').json" \
              --overwrite true
